
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  datasource:
    name: oabg  #数据库名
    url: jdbc:oracle:thin:@localhost:1521:xe #url
    username: system  #用户名
    password: jiangwen  #密码
    driver-class-name: oracle.jdbc.driver.OracleDriver #数据库链接驱动

#thymeleaf:
#  prefix: classpath:/templates/  #prefix：指定模板所在的目录
#  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
#  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
#  suffix:  .html
#  #encoding: UTF-8
#  #content-type: text/html
#  mode: HTML5
